# this is going to be the creation of the Character class
# within this class will be a few different types of characters, but they will all have some similarities...
# name, race, age, height, weight, class, stat block,